proxy:
  port: 8080
  landing-page: /app/direg
  authentication: none
  container-log-path: ./container-logs
  container-backend: docker
  container-wait-time: 10000
  heartbeat-rate: 1000
  heartbeat-timeout: 300000
  hide-navbar: true
  docker:
    internal-networking: true
  specs:
   - id: paperqa
    display-name: PaperQA Service
    description: PaperQA Service for Document Processing
    container-network: direg-net
    container-image: paperqa-endpoint:V0
    port: 5555
    
  - id: direg
    display-name: DiREG
    description: DiReG WebApp
    container-network: direg-net
    container-image: direg:V0
    # port: 3232 #explicit configuration probably not necessary;
    container-volumes: 
      - "../../app/login:/srv/shiny-server/login"
      - "../../app/data:/srv/shiny-server/data"
      - "../../app/refGenome:/srv/shiny-server/refGenome"
    port: 3232

logging:
  file:
    name: ./shinyproxy.log
server:
  useForwardHeaders: true
  servlet:
    context-path: /direg

